Frontendtesting
NikBit101/dcalc_ext pull request #1
Opened 2023-03-25 04:48 UTC by UP2021407

# Added UP number text field input and on page display functionality.

1. Put UP number in and press enter
2. If text input does not start with "UP" it tells you Error
3. If UP number is accepted it tells you student data is being loaded for that UP number.

Not my css, ref:
[CSS Reference](https://uiverse.io/Satwinder04/pink-bat-77)

2023-03-25 09:57 UTC, NikBit101 requested changes
Looks good. I would recommend forcing an upper case automatically, so the user won't need to do it manually.

Put this inside the input element in up-input field: style="text-transform: uppercase;"

Change line 13 inside the ui.js file to this: if (!inputField.value.toUpperCase().startsWith("UP")) {

2023-03-25 12:31 UTC, m0urao commented
In my opinion, I think we should follow the design that the page has, for example, the input for the modules. I think we should follow the same style, either we change the UP input or we change all the others to keep everything the same. Again, it's just an opinion.

2023-03-25 12:32 UTC, m0urao reviewed
I like it, however, I think we should follow the design that the page has, for example, the input for the modules. I think we should follow the same style, either we change the UP input or we change all the others to keep everything the same. Again, it's just an opinion.

2023-03-25 12:51 UTC, m0urao commented on index.html
> +      <label for="input" class="label">Enter UP number:</label>
Also, I think there's an overkill of information here. Like you have a header with "Input your UP number to get your data:" and then you say again the same thing in the input "Enter UPnumber". I would say this instead:
```<label for="input" class="label">UPXXXXXX</label>```

2023-03-26 00:13 UTC, wgw0 commented
### Changes following review

1. Forced uppercase with Nik's code

2. Removed instructional header + altered text-input text

2023-03-26 08:54 UTC, NikBit101 approved these changes

2023-03-26 09:36 UTC, merged