#server-side changes
NikBit101/dcalc_ext pull request #5
Opened 2023-03-28 11:41 UTC by NikBit101

Moved the whole page into client folder, assigned request handler on server-side using express.js

Display a warning message for user if the ID does not have student's data in database.

2023-03-28 18:19 UTC, wgw0 requested changes
Is this supposed to remove functionality of sliders/locks?
Or was the idea to merge this first then merge my branch afterwards to restore functionality?

2023-03-28 18:19 UTC, wgw0 commented on client/index.html
Are we removing the lock and sliders functionality?
Why does this branch delete these elements and functionality?

2023-03-28 18:19 UTC, wgw0 commented on client/js/ui.js
Similar question, why is this functionality removed?
Is it because you are planning on merging my pull request after and taking the functionality from that one instead?

2023-03-28 18:20 UTC, NikBit101 commented on client/js/ui.js
I was working on it whilst you do front-end implementation. No, it's not supposed to delete your work but rather merge along with front-end

2023-03-28 18:22 UTC, wgw0 commented on client/js/ui.js
Okay that's fine then. It all looks good to me, haven't tested functionality yet. Will do now.

2023-03-29 00:03 UTC, wgw0 approved these changes

2023-03-29 00:07 UTC, wgw0 commented
Just need to remove node_modules from the branch again and then I think it's fine to merge

2023-03-29 09:48 UTC, wgw0 approved these changes
All good, I think.
I get SSL errors when I execute it on my end but I don't think that's a code issue.
Feel free to merge this then I will try merge my sliders branch afterwards.

2023-03-29 10:27 UTC, m0urao commented
> 

change the path in the ```package.json```

2023-03-29 10:28 UTC, m0urao commented
> All good, I think. I get SSL errors when I execute it on my end but I don't think that's a code issue. Feel free to merge this then I will try merge my sliders branch afterwards.

change the path in the ```package.json```

2023-03-29 10:29 UTC, m0urao commented
Also, @wgw0 , when you run this, make sure you get a response from server on ```student-request.js```. It should change the label warning the user about wrong student id.

2023-03-29 11:12 UTC, m0urao approved these changes

2023-03-29 11:13 UTC, merged